# -*- coding: utf-8 -*-
"""estrutura de repetição.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125IBOH6N7diep7kPDWLSxEivU90LOtAa
"""

lista = ['zé', 'ana', 'clara',]
#lista_ordenada = sorted(lista)            //assim tbm vai
lista.sort()
for pessoa in lista :
  print(pessoa)

nome = 'igor'
for letra in nome :
  print(letra)

total = 50
for c in range(0,total+1,1):
  print(c)

num = int(input('digite o total de numero a ser analisado'))
for c in range (1,num+1,1):
  if (c % 2 == 0):
    print(f'{c} é par')
  else :
    print(f'{c} é impar')

i = 1
while i <= 6 :
  print(i)
  i+=1

