# -*- coding: utf-8 -*-
"""listas2 e função.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFVE1GlsnF0x1NA0ZBBMA3VwO6BvUXUZ
"""

lista1 = ['a', 'b', 'c', 'd', 'e', 'f']
print(len(lista1))

palavra = 'detergente'
print(len(palavra))
print(palavra[5:10])

l = [5,4,2]
l[1] = 10
print(l)
lista = l + [11,12,13]
print(lista)

def soma(x,y):    #função
  soma = x + y
  return soma

soma(1,2)

lista1 = [19, 'python', True, 86, 100]

def tipos(lista):
  resposta = []
  x=0
  while x < 5 :
    tipoVariavel = type(lista[x])
    resposta.insert(x,tipoVariavel)
    x+=1
  return resposta

tipos(lista1)

lista1 = [19, 'python', True, 86, 100]
lista1.insert(2, False)       #insere algo na lista
print(lista1)
lista1.remove('python')       #remove um iten apartir do seu nome
print(lista1)
print(lista1.count(19))       #conta quantas vzs essa variavel aparece na lista
lista1.pop(2)                 #apaga uma variavel do array apartir do seu indice
print(lista1)

brasil = [
          'nordeste',
          ['pernambuco', ['recife','goiania']],
          ['rio grande do norte',['natal']],
          ['alagoas',['maceio']],
          'norte',
          ['Amazonas', 'acre', 'Pará']
         ]
print(brasil[3][1])