# -*- coding: utf-8 -*-
"""Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohVUNZ-QHLc2B0kN9GCnk-rf3dCij41K
"""

idade_renata = 14
idade_fabiana = 10
dinheiro_iara = 5000.00

if ( idade_renata >= 14 and idade_fabiana == 18 or dinheiro_iara == 5000.00 ) :
  situacao = 'vai viajar'
else:
    situacao = 'não vai viajar'

print(f'rodrigo {situacao}')

sabesambar = 'sim'
gostafeijoada = 'sim'
torcedorselecao = 'nao'

if ( sabesambar == 'sim' or gostafeijoada == 'nao' and torcedorselecao == 'sim') :
  print('esse e brasileiro')
else :
  print('esse não e brasileiro')

temDentes = 'sim'
temFome = 'nao'
gosta = 'sim'

if ( temDentes == 'sim' and temFome == 'nao') :
  temDenteFomecondicao = 'sim'
else:
  temDenteFomecondicao = 'nao'

print(temDenteFomecondicao)

if( temDenteFomecondicao == 'nao' or gosta =='sim') :
  print('vai comer')
else :
  print('não vai comer')

temDentes = 'sim'
temFome = 'nao'
gosta = 'sim'

if (temDentes == 'sim') :
  TDcondicao = 'Verdadeiro'
elif (temDentes == 'nao') :
  TDcondicao = 'Falso'

if (temFome == 'nao') :
  TFcondicao = 'Falso'
elif (temFome == 'nao') :
  TFcondicao = 'Falso'

if (gosta == 'sim') :
  Gcondicao = 'Verdadeiro'
elif (gosta == 'nao') :
  Gcondicao = 'Falso'

if (Gcondicao == 'falso' or TFcondicao == 'false') :
  GTFcondicao = 'falso'
else :
  GTFcondicao = 'verdadeiro'

if ( GTFcondicao == 'verdadeiro' and TDcondicao == 'verdadeiro') :
  Fcondicao = 'verdadeiro'
else :
  Fcondicao = 'falso'

print(f'A pessoa precisa ter dentes {TDcondicao} e ter fome {TFcondicao} ou gostar de maçã {Gcondicao}')