# -*- coding: utf-8 -*-
"""par ou impar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYXtcbcyV7pCHl3pkQo2cwyyZyICHBbC
"""

numero = int(input('digite o número: '))

if numero % 2 == 0:
  print(f'o numero {numero} é par')
else:
  print(f'o numero {numero} é impar')